### PR TITLE
Update rust-analyzer VSCode extension name

### PR DESCRIPTION
**Pull request by youduda**
[rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) has a new name.

### CODE REVIEW

**Comment by SergioGasquez** [comment]
Thanks for updating the extension!

**Comment by youduda** [comment]
One addition to rust-analyzer.
For me, it only works when I add `"postCreateCommand": "cargo install espflash && cargo install cargo-pio && rustup default esp",` into devcontainer.json. Do you have a similar addition?

**Comment by SergioGasquez** [comment]
Hello @youduda, thanks for your comment! This repo is sort of "outdated", we started our investigations of devcontainers with it, but we have evolved a lot during the last weeks. Let me quickly update it! In the meantime, feel free to have a look at this repo: https://github.com/georgik/rustzx-esp32 . It`s a real project with full devcontainer supports:
- Development enviromnet ready (in VsCode, Gitpod and GH Codespaces)
-Support for Wokwi simulation
  - GDB debugging with Wokwi
- Flashing

As you can see in the rustzx, we are building the container from a Dockerfile and not using images hosted on Dockerhub. We are also working on this at the moment. In the upcoming days, we will transfer all the CI building images from [esp-rs-container](https://github.com/SergioGasquez/esp-rs-container) to [rust-build](https://github.com/esp-rs/rust-build) and the generated images will live in [espressif/idf-rust](https://hub.docker.com/r/espressif/idf-rust). Then we will update the repos to give user the choice to pull images or build them from a Dockerfile.

**Comment by SergioGasquez** [comment]
Hello @youduda! Quick update:
- I have updated this repo, follow the instructions to use with your own project and let me know if you have any questions/suggestions!
- I have updated [esp-template](https://github.com/SergioGasquez/esp-template) to include devcontainer support, feel free to use it for `no_std` projects. Is better than using esp-rs-devconatiner because cargo-generate takes care of configuring the project with the proper mcu, paths, and names that you need to manually set them as in this repo as is way more general.
  - I will create a PR to merge the changes into [esp-rs/esp-template](https://github.com/esp-rs/esp-template)
- I will be doing the same with [esp-idf-template](https://github.com/esp-rs/esp-idf-template) in the upcoming days, I'll update you once is done!

In the meantime, if you have any questions or suggestions, just let me know!

**Comment by youduda** [comment]
This looks awesome and works like a charm! Didn't expect that programming with Rust on ESP works that easy out of the box like other projects do (e.g. RIOT).

We are just starting with our project, so we don't know yet if we want to use `no_std`. It's only educational and since I never worked without `std` before, I guess I take the chance to learn something new.

Thanks for the offer, I will let you know when we face any issues.

**Comment by SergioGasquez** [comment]
Hi! Really happy to hear that is working for you! It was not only my work but the whole espressif rust team! :raised_hands:  

I already did the same thing for our `std` template: https://github.com/SergioGasquez/esp-idf-template, I will be opening PR to merge them into the esp-rs repos soon!

> Thanks for the offer, I will let you know when we face any issues.

No problem! Just let us know if we can help in any way :blush:

**Comment by SergioGasquez** [comment]
By the way! I forgot to mention a few things that might be helpful:
- We have a matrix channel where you can also ask any questions: https://matrix.to/#/#esp-rs:matrix.org
- We have biweekly community meetings, feel free to join! In this matrix channel, you can see the next one: https://matrix.to/#/#esp-rs-community-meetins:matrix.org
- We are currently doing training with Ferrous System: https://github.com/ferrous-systems/espressif-trainings 
  - We are also improving this repo with devcontainers to improve user's experience!

**Pull request closed without merging**
